/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-09-27 16:21:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <title>Fake News</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Center the loader */\r\n");
      out.write("        #loader {\r\n");
      out.write("          position: absolute;\r\n");
      out.write("          left: 50%;\r\n");
      out.write("          top: 55%;\r\n");
      out.write("          z-index: 1;\r\n");
      out.write("          width: 120px;\r\n");
      out.write("          height: 120px;\r\n");
      out.write("          margin: -76px 0 0 -76px;\r\n");
      out.write("          border: 12px solid #f3f3f3;\r\n");
      out.write("          border-radius: 50%;\r\n");
      out.write("          border-top: 12px solid #80aaff;\r\n");
      out.write("          animation: spin 2s linear infinite;\r\n");
      out.write("        }\r\n");
      out.write("    @keyframes spin {\r\n");
      out.write("      0% { transform: rotate(0deg); }\r\n");
      out.write("      100% { transform: rotate(360deg); }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    </style>        \r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width\">\r\n");
      out.write("	\r\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function loaddoc() {\r\n");
      out.write("            \r\n");
      out.write("				\r\n");
      out.write("            if (document.getElementById(\"sample\").value == \"\")\r\n");
      out.write("                alert(\"please enter the text in the box\");\r\n");
      out.write("            else if(document.getElementById(\"choose\").value==\"All\")\r\n");
      out.write("                {\r\n");
      out.write("                     AllHeading();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("            else {\r\n");
      out.write("                document.getElementById(\"datasave\").innerText = \"\";\r\n");
      out.write("                var xhttp = new XMLHttpRequest();\r\n");
      out.write("                xhttp.onreadystatechange = function () {\r\n");
      out.write("                    if (this.readyState == 4 && this.status == 200) {\r\n");
      out.write("                        \r\n");
      out.write("                        document.getElementById(\"id1\").innerHTML = this.responseText;\r\n");
      out.write("                        showPage();\r\n");
      out.write("                        \r\n");
      out.write("                    }\r\n");
      out.write("                };\r\n");
      out.write("                var url = \"/process.jsp?sample=\" + document.getElementById(\"sample\").value + \"&choose=\" + document.getElementById(\"choose\").value+\"&run=1\";\r\n");
      out.write("                console.log(url);\r\n");
      out.write("                xhttp.open(\"GET\", url, true);\r\n");
      out.write("                xhttp.send();\r\n");
      out.write("                StartAnimation();\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        </script>\r\n");
      out.write("        <script>\r\n");
      out.write("            function loaddoc2() {\r\n");
      out.write("            if (document.getElementById(\"sample2\").value === \"\")\r\n");
      out.write("                alert(\"please enter the text in the box\")\r\n");
      out.write("            else if(document.getElementById(\"choose2\").value===\"All\")\r\n");
      out.write("\r\n");
      out.write("            {\r\n");
      out.write("                All();\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("                var xhttp = new XMLHttpRequest();\r\n");
      out.write("                xhttp.onreadystatechange = function () \r\n");
      out.write("                {\r\n");
      out.write("                    if (this.readyState == 4 && this.status == 200) \r\n");
      out.write("                    {\r\n");
      out.write("                        document.getElementById(\"id1\").innerHTML = this.responseText;\r\n");
      out.write("                        showPage();\r\n");
      out.write("                    }\r\n");
      out.write("                };\r\n");
      out.write("                var url2 = \"/process.jsp?sample2=\" + document.getElementById(\"sample2\").value + \"&choose2=\" + document.getElementById(\"choose2\").value+\"&run=1\";\r\n");
      out.write("                console.log(url2);\r\n");
      out.write("                xhttp.open(\"GET\", url2, true);\r\n");
      out.write("                xhttp.send();\r\n");
      out.write("                StartAnimation();\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        function SendHeading(i,mxCnt){\r\n");
      out.write("					\r\n");
      out.write("					var xhr=[];\r\n");
      out.write("					var j;\r\n");
      out.write("                xhr[i] = new XMLHttpRequest();\r\n");
      out.write("					j=i+1;\r\n");
      out.write("                    \r\n");
      out.write("                url = \"/process.jsp?sample=\" + document.getElementById(\"sample\").value + \"&choose=Model\"+j+\"&run=\"+j ;					\r\n");
      out.write("                xhr[i].open(\"GET\", url, true);\r\n");
      out.write("                xhr[i].onreadystatechange = function(){\r\n");
      out.write("                    if (xhr[i].readyState === 4 && xhr[i].status === 200){\r\n");
      out.write("                        if(i==0){\r\n");
      out.write("									document.getElementById(\"id1\").innerHTML =this.responseText;\r\n");
      out.write("							}\r\n");
      out.write("							else{\r\n");
      out.write("							 document.getElementById(\"id1\").innerHTML = document.getElementById(\"id1\").innerHTML+this.responseText;\r\n");
      out.write("							}\r\n");
      out.write("							 if (i <mxCnt){\r\n");
      out.write("                                SendHeading(i+1,mxCnt)\r\n");
      out.write("                                \r\n");
      out.write("								}\r\n");
      out.write("                                else if(i == mxCnt){\r\n");
      out.write("                                    showPage();\r\n");
      out.write("                                }\r\n");
      out.write("                    }\r\n");
      out.write("                };\r\n");
      out.write("					\r\n");
      out.write("               xhr[i].send();\r\n");
      out.write("               \r\n");
      out.write("            }  \r\n");
      out.write("\r\n");
      out.write("function AllHeading()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		  let  i=0;\r\n");
      out.write("		  let mxCnt=3;\r\n");
      out.write("          StartAnimation();\r\n");
      out.write("		  SendHeading(i,mxCnt);  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("} //end function All\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function Send(i,mxCnt){\r\n");
      out.write("					\r\n");
      out.write("					var xhr=[];\r\n");
      out.write("					var j;\r\n");
      out.write("                xhr[i] = new XMLHttpRequest();\r\n");
      out.write("					j=i+1;\r\n");
      out.write("                    \r\n");
      out.write("                url = \"/process.jsp?sample2=\" + document.getElementById(\"sample2\").value + \"&choose2=Model\"+j+\"&run=\"+j ;					\r\n");
      out.write("                xhr[i].open(\"GET\", url, true);\r\n");
      out.write("                xhr[i].onreadystatechange = function(){\r\n");
      out.write("                    if (xhr[i].readyState === 4 && xhr[i].status === 200){\r\n");
      out.write("                        if(i==0){\r\n");
      out.write("									document.getElementById(\"id1\").innerHTML =this.responseText;\r\n");
      out.write("							}\r\n");
      out.write("							else{\r\n");
      out.write("							 document.getElementById(\"id1\").innerHTML = document.getElementById(\"id1\").innerHTML+this.responseText;\r\n");
      out.write("							}\r\n");
      out.write("							 if (i <mxCnt){\r\n");
      out.write("									Send(i+1,mxCnt)\r\n");
      out.write("								}\r\n");
      out.write("                                else if(i == mxCnt){\r\n");
      out.write("                                    showPage();\r\n");
      out.write("                                }\r\n");
      out.write("                    }\r\n");
      out.write("                };\r\n");
      out.write("					\r\n");
      out.write("               xhr[i].send();\r\n");
      out.write("               \r\n");
      out.write("            }  \r\n");
      out.write("\r\n");
      out.write("function All()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		  let  i=0;\r\n");
      out.write("		  let mxCnt=3;\r\n");
      out.write("          StartAnimation();\r\n");
      out.write("		  Send(i,mxCnt);  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("} //end function All\r\n");
      out.write("\r\n");
      out.write("function showPage() {\r\n");
      out.write("  document.getElementById(\"loader\").style.display = \"none\";\r\n");
      out.write("  document.getElementById(\"TableHeader\").style.display = \"block\";\r\n");
      out.write("  document.getElementById(\"id1\").style.display = \"block\";\r\n");
      out.write("  document.getElementById(\"NewsHeadline\").style.display = \"block\";\r\n");
      out.write("  document.getElementById(\"NewsContent\").style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("function Start() {\r\n");
      out.write("  document.getElementById(\"loader\").style.display = \"none\";\r\n");
      out.write("  document.getElementById(\"TableHeader\").style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("function StartAnimation() {\r\n");
      out.write("  document.getElementById(\"loader\").style.display = \"block\";\r\n");
      out.write("  document.getElementById(\"TableHeader\").style.display = \"none\";\r\n");
      out.write("  document.getElementById(\"id1\").style.display = \"none\";\r\n");
      out.write("  document.getElementById(\"NewsHeadline\").style.display = \"none\";\r\n");
      out.write("  document.getElementById(\"NewsContent\").style.display = \"none\";\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <style>\r\n");
      out.write("        h1,\r\n");
      out.write("        h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            height: fit-content;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .tab1 {\r\n");
      out.write("            tab-size: 2;\r\n");
      out.write("        }\r\n");
      out.write("  \r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"Start()\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\" style=\"text-align:center; background-color:rgb(118, 181, 215); color:black; margin: 0\">\r\n");
      out.write("            <div class=\"col-sm-2\">\r\n");
      out.write("                <img  src=\"CDAC-LOGO.png\" style=\"width: 50%; height: 69px;\" >\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-8\">\r\n");
      out.write("                <h1 style=\"font-family: Georgia, Times, serif, Times, serif \">Fake News Detection System</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-2\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <h2 style=\"background-color:rgba(208, 212, 93, 0.994); padding: 40px 0px;\"> সত্যান্বেষী সংবাদ\r\n");
      out.write("            <p style=\"font-size: medium;font-style: italic;\">Know what you read is How much \"true\"</p>\r\n");
      out.write("        </h2>\r\n");
      out.write("        <br></br>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        <p id=\"NewsHeadline\" >\r\n");
      out.write("            <a class=\"btn btn-info btn-lg btn-block\" data-toggle=\"collapse\" \r\n");
      out.write("            href=\"#collapseExample\" role=\"button\" aria-expanded=\"false\" aria-controls=\"collapseExample\" \r\n");
      out.write("            data-toggle=\"collapse\" href=\"#collapse1\" class=\"\" aria-expanded=\"true\">Check News Headline\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"collapse\" id=\"collapseExample\">\r\n");
      out.write("                <div class=\"card card-body\">\r\n");
      out.write("                    <!-- <form action=\"/process.jsp\" method=\"get\" class=\"text-center\" > -->\r\n");
      out.write("                        <form style=\"margin: 0px 300px;padding: 0px 0px ; text-align:center\" action=\"/process.jsp\" method=\"get\" >\r\n");
      out.write("                        <input style=\"color: rgb(3, 1, 5);\" type=\"text\" id=\"sample\" placeholder=\"Please Enter the News...\" size=\"70\">\r\n");
      out.write("                        <br></br>\r\n");
      out.write("                        <input type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseExample\" aria-expanded=\"false\" \r\n");
      out.write("                        aria-controls=\"collapseExample\" style=\"background-color:DodgerBlue;\" type=\"button\" onclick=\"loaddoc()\" \r\n");
      out.write("                        class=\"btn btn-primary\" value=\"Check...\">\r\n");
      out.write("                \r\n");
      out.write("                        <select style=\"background-color:rgb(5, 146, 29);\" id=\"choose\" class=\"btn btn-primary\">\r\n");
      out.write("                            <option value=\"Model1\">Model1</option>\r\n");
      out.write("                            <option value=\"Model2\">Model2</option>\r\n");
      out.write("                            <option value=\"Model3\">Model3</option>\r\n");
      out.write("                            <option value=\"Model1\">Model4</option>\r\n");
      out.write("                            <option value=\"All\">All</option>   \r\n");
      out.write("                        </select>\r\n");
      out.write("                    </form>   \r\n");
      out.write("    </p>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <br></br>\r\n");
      out.write("        <p id=\"NewsContent\" >\r\n");
      out.write("            <a class=\"btn btn-info btn-lg btn-block\" data-toggle=\"collapse\" href=\"#collapseExample2\" \r\n");
      out.write("            role=\"button\" aria-expanded=\"false\" aria-controls=\"collapseExample2\" data-toggle=\"collapse\" \r\n");
      out.write("            href=\"#collapse1\" class=\"\" aria-expanded=\"true\">Check News content\r\n");
      out.write("             </a>\r\n");
      out.write("    \r\n");
      out.write("            <div class=\"collapse\" id=\"collapseExample2\">\r\n");
      out.write("                <div class=\"card card-body\">\r\n");
      out.write("    \r\n");
      out.write("                    <style>\r\n");
      out.write("                        textarea \r\n");
      out.write("                        {\r\n");
      out.write("                        width: 500px;\r\n");
      out.write("                        height: 150px;\r\n");
      out.write("                        }  \r\n");
      out.write("                        \r\n");
      out.write("                     </style>  \r\n");
      out.write("                      \r\n");
      out.write("        <form style=\"margin: 0px 350px;padding: 0px 0px ; text-align:center\" action=\"/process.jsp\" method=\"get\" >\r\n");
      out.write("            \r\n");
      out.write("            <textarea class=\"text-warning bg-black\" id=\"sample2\" placeholder=\"Please enter the News content\"  rows=\"3\"></textarea>\r\n");
      out.write("            <br></br>\r\n");
      out.write("                     \r\n");
      out.write("            <input type=\"button\"  data-target=\"#collapseExample2\" aria-expanded=\"false\" aria-controls=\"collapseExample2\" style=\"background-color:DodgerBlue;\" type=\"button\" onclick=\"loaddoc2()\" class=\"btn btn-primary\" value=\"Check...\">\r\n");
      out.write("    \r\n");
      out.write("            <select style=\"background-color:rgb(5, 146, 29);\" id=\"choose2\" class=\"btn btn-primary\">\r\n");
      out.write("               \r\n");
      out.write("                <option value=\"Model1\">Model1</option>\r\n");
      out.write("                <option value=\"Model2\">Model2</option>\r\n");
      out.write("                <option value=\"Model3\">Model3</option>\r\n");
      out.write("                <option value=\"Model1\">Model4</option>\r\n");
      out.write("                <option value=\"All\">All</option>\r\n");
      out.write("    \r\n");
      out.write("            </select>\r\n");
      out.write("        </form>\r\n");
      out.write("    </p>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br></br>\r\n");
      out.write("    <br></br>\r\n");
      out.write("    <div id=\"loader\">\r\n");
      out.write("    </div>\r\n");
      out.write("     <div id=\"TableHeader\" class=\"text-center\"> <h3 style=\"font-family: Times New Roman, Times, serif \"> <b>Predicted Result</b></h3> </div>\r\n");
      out.write("     <div id=\"id1\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"id2\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"id3\">\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        function btnfun(){\r\n");
      out.write("            let text;\r\n");
      out.write("            if (confirm(\"Do you want to save or not?\") == true) {\r\n");
      out.write("                console.log('helo');\r\n");
      out.write("                \r\n");
      out.write("                    function datasave(){\r\n");
      out.write("                        console.log(\"inside function\");\r\n");
      out.write("    \r\n");
      out.write("            \r\n");
      out.write("                    var xhttp = new XMLHttpRequest();\r\n");
      out.write("                    xhttp.onreadystatechange = function () {\r\n");
      out.write("                        if (this.readyState == 4 && this.status == 200) {\r\n");
      out.write("                            \r\n");
      out.write("                            document.getElementById(\"datasave\").innerHTML = this.responseText;\r\n");
      out.write("                            // showPage();\r\n");
      out.write("                            \r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                    \r\n");
      out.write("                    var url = \"/create.jsp?decision=\" + document.getElementById(\"id33\").value + \"&input=\" + document.getElementById(\"input2\").innerText.trim()+\"&run=2\";\r\n");
      out.write("                    \r\n");
      out.write("                    console.log(url);\r\n");
      out.write("                    xhttp.open(\"GET\", url, true);\r\n");
      out.write("                    xhttp.send();\r\n");
      out.write("                }\r\n");
      out.write("                datasave();\r\n");
      out.write("      } else {\r\n");
      out.write("        text = \"You canceled!\";\r\n");
      out.write("        console.log('cancel');\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("      </script>\r\n");
      out.write("      <div id=\"datasave\"></div>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
